# Generated by Django 6.0.5 on 2026-05-29 03:05

import champinones.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PERSONAL', 'Personal'), ('VIP', 'Miembro VIP')], default='PERSONAL', max_length=10, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_ventas_boletos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total por Venta de Boletos (BOB)')),
                ('total_recargas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total por Recargas (BOB)')),
                ('total_recaudado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Recaudado (BOB)')),
                ('cantidad_boletos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Boletos Vendidos')),
                ('cantidad_recargas', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Recargas Procesadas')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=8, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del Cierre')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora del Cierre')),
                ('usuario_cierre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Evento')),
                ('equipo_local', models.CharField(max_length=100, verbose_name='Equipo Local')),
                ('equipo_visitante', models.CharField(max_length=100, verbose_name='Equipo Visitante')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Base (BOB)')),
                ('capacidad_total', models.PositiveIntegerField(verbose_name='Capacidad Total')),
                ('capacidad_disponible', models.PositiveIntegerField(verbose_name='Capacidad Disponible')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=12, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='MiembroVIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='La CI debe tener entre 5 y 8 dígitos numéricos.', regex='^\\d{5,8}$')], verbose_name='Cédula de Identidad')),
                ('complemento', models.CharField(blank=True, help_text='Solo si existe duplicidad (ej: 1A, 3C).', max_length=2, validators=[django.core.validators.RegexValidator(message='El complemento debe tener exactamente 2 caracteres alfanuméricos (ej: 1A, 3C).', regex='^[A-Za-z0-9]{2}$')], verbose_name='Complemento CI')),
                ('extension', models.CharField(choices=[('LP', 'La Paz'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CH', 'Chuquisaca'), ('TJ', 'Tarija'), ('BE', 'Beni'), ('PD', 'Pando')], max_length=2, verbose_name='Extensión (Departamento)')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('celular', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='El celular debe tener 8 dígitos y comenzar con 6, 7 u 8.', regex='^[678]\\d{7}$')], verbose_name='Celular')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo (BOB)')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=12, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembro_vip', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
            options={
                'verbose_name': 'Miembro VIP',
                'verbose_name_plural': 'Miembros VIP',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('GENERAL', 'General'), ('PREFERENTE', 'Preferente'), ('VIP', 'VIP'), ('PALCO', 'Palco')], default='GENERAL', max_length=12, verbose_name='Sector')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Pagado (BOB)')),
                ('codigo', models.CharField(default=champinones.models.generar_codigo_boleto, editable=False, max_length=12, unique=True, verbose_name='Código Único')),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('pago_con_saldo_vip', models.BooleanField(default=False, verbose_name='Pagado con Saldo VIP')),
                ('vendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendido por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='champinones.evento', verbose_name='Evento')),
                ('miembro_vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='champinones.miembrovip', verbose_name='Miembro VIP')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Monto (BOB)')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('QR', 'Pago por QR')], default='EFECTIVO', max_length=15, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recargas', to='champinones.miembrovip', verbose_name='Miembro VIP')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Recarga',
                'verbose_name_plural': 'Recargas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddConstraint(
            model_name='miembrovip',
            constraint=models.UniqueConstraint(fields=('ci', 'complemento', 'extension'), name='unique_ci_complemento_extension'),
        ),
    ]
