# Generated by Django 5.2.7 on 2026-05-29 09:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champinones', '0002_agregar_campos_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Inicial (BOB)')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Apertura')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de Apertura')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to=settings.AUTH_USER_MODEL, verbose_name='Abierto por')),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
