# Generated by Django 5.2.7 on 2026-05-29 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champinones', '0003_agregar_apertura_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('GENERAL', 'General'), ('PREFERENTE', 'Preferente'), ('VIP', 'VIP'), ('PALCO', 'Palco')], max_length=12, verbose_name='Sector')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio (BOB)')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_sector', to='champinones.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Precio por Sector',
                'verbose_name_plural': 'Precios por Sector',
                'unique_together': {('evento', 'sector')},
            },
        ),
    ]
